### ISSUE TITLE
Running test set up throwing error message

### ISSUE THREAD

**Issue by shellhatcher** [dwyl/todo-list-javascript-tutorial#10]
Hi,

I tried to run the code given for the test set up purpose using   node test/todo-app.test.js
that should return nothing, but I got  the following error messages 
**internal/modules/cjs/loader.js:615**
    **throw err;**
    **^**

**Error: Cannot find module 'tape'**
    **at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)**
    **at Function.Module._load (internal/modules/cjs/loader.js:539:25)**
    **at Module.require (internal/modules/cjs/loader.js:667:17)**
    **at require (internal/modules/cjs/helpers.js:20:18)**
    **at Object.<anonymous> (/Users/babydust/Desktop/todolist_mvc/test/todo-app.test.js:1:76)**
    **at Module._compile (internal/modules/cjs/loader.js:738:30)**
    **at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)**
    **at Module.load (internal/modules/cjs/loader.js:630:32)**
    **at tryModuleLoad (internal/modules/cjs/loader.js:570:12)**
    **at Function.Module._load (internal/modules/cjs/loader.js:562:3)**

What might cause this problem to occur? 
Thank you in advance for your assistance.

**Comment by shellhatcher** [comment]
Hi, Nelson

Great to have such a swift reply from you, really appreciate that:)

I'll try to run non install and let you know the result afterward.



2019年2月25日(月) 17:14 Nelson <notifications@github.com>:

**Comment by shellhatcher** [comment]
I am sorry, was it nom install or npm install?


2019年2月25日(月) 21:27 sweetandsour 1001 <sweetandsour1001@gmail.com>:

**Comment by fmoliveira** [comment]
Hi @shellhatcher, it's `npm install`. Please try running it and let us know. :)

**Comment by nelsonic** [comment]
@shellhatcher that was Android auto-correcting "npm" to "nom" ... 🙄 
it needs to be **`npm install`** as @felipeorlando kindly corrected. 👍

**Comment by nelsonic** [comment]
@shellhatcher that was Android auto-correcting "npm" to "nom" ... 🙄 
it needs to be **`npm install`** as @fmoliveira kindly corrected. 👍

**Comment by shellhatcher** [comment]
Thanks Felipe and Nelson

My keyboard also does autocorrect often, I can understand that:)

Before I did the npm install, I checked it's availability by using npm -v,
and the terminal gave me its version, which means it already there.

So, do I still need to run npm install on the terminal?

Thank you

2019年2月25日(月) 23:33 Nelson <notifications@github.com>:

**Comment by fmoliveira** [comment]
@shellhatcher The command `npm -v` will output the installed version of `npm`, the Node.js Package Manager itself, not anything related to tape. So, running `npm -v` isn't sufficient to tell if you've got tape installed.

To check if you've got `tape` installed in your current repository, check your `node_modules` folder, that should be in the same level as your `package.json` file. Does this folder exist? Does a `tape` folder exist inside it? If yes, then `tape` is installed, and you shouldn't need to run `npm install` again.

**Comment by shellhatcher** [comment]
Thanks Filipe,

I got everything now, tape is installed in the todolist-javascript-tutorial
cloned from your repo.

There is a CREATE FILE step which asked to make the three files
1. test/todo-app.test.js
2.lib/todo-app.js
3.index.html

Question is :

1. Should create these files in a new directory separated from the one I
cloned from your repo( todolist-javascript-tutorial) ?

2. And if so, do I need to run npm install in this directory?
Actually, I did run npm install in this new directory, but can't get the
tape installed. Hence I still got the same error message.
Any suggestion?

3. Or within the same directory with the one I cloned from your repo
(todolist-javascript-tutorial)
?
But, this one is impossible, since all those three files are there already.

4.  I am now trying to read your TDD tutorial to try to understand about
this testing stuff, did I go the right direction?

5. Any suggestion what need to be done before jumping into this tutorial to
smoothen the process in following the todolist MVC vanilla JS tutorial?

Many thanks in advance, and pardon for me asking too many questions.



2019年2月26日(火) 12:28 Filipe Oliveira <notifications@github.com>:

**Comment by Jbarget** [comment]
@shellhatcher the answer is 3.

The 3 files need to be within the directory so that the code has access to the `node_modules` directory. The `node_modules` directory contains all the "dependencies" for the project. (If you had a different project, they would likely have different "dependencies" and therefore the contents of the `node_modules` directory would be different too.)

You can see these in the `package.json` file under `dependencies` and `devDependencies`.
And you can think of the `package.json` as a whole as the ingredients list for the project. 
 

Questions are fine :) If you have any suggestions for us on how to make the README clearer let us know!

**Comment by shellhatcher** [comment]
Thank you very much Justen Barget for the answer.
I did your suggestion and it worked fine now:) -But I changed the name of the files, since the files names asked are all already existed inside the todo-list-javascript-tutorial directory.

In my humble opinion as a total beginner, probably the following could be used to make the README totally beginner friendly: 

1. The HOW? section should be numbered in order, so it will be easy for us to follow along spot at which step we are.
2. I think putting the seemingly unrelated information in the middle of the HOW? step will cause distraction, for example at the README after the first HOW? section, all of a sudden we are introduced with Elm(ish) ?. I think all of the necessary additional information/ the explanation on a certain buzz words should be group on their own.


Probably that's all for now, since I haven't moved further. Later down the road, if I find something else I will raise an issue and probably I'll be able to give more suggestions seen from newbie point of view.

I do really appreciate great support from all of you guys

**Comment by nelsonic** [comment]
@shellhatcher thanks for the incredibly valuable feedback! 🎉

**Comment by shellhatcher** [comment]
＠Nelson and all of the others

It was nothing compared to your noble willingness to share your knowledge
and to give the support:)

2019年2月26日(火) 20:49 Nelson <notifications@github.com>:

**Comment by nelsonic** [comment]
@shellhatcher please confirm if you were able to get the example (and tests) running.
(_if you were, please consider commenting and closing this issue, thanks!_) ✨

**Comment by shellhatcher** [comment]
@nelsonic,
Pardon me for haven't closed the issue yet. I have successfully got the example and tests running since 25 days ago thanks to all of your swift supports:)
