### ISSUE TITLE
Simplify Title?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/todo-list-javascript-tutorial#11]
At present the title (H1) and subtitle (intro) are quite technical:
![screenshot_20190226-100140](https://user-images.githubusercontent.com/194400/53404491-b593d280-39ad-11e9-94f5-5b529eb4d61d.png)
I hypothesise that this is somewhat "off-putting" to complete beginners
Who might be overwhelmed by all the words.
What do people think of the idea of simplifying it to something a bit more concise?

Suggestions very much welcome!

**Comment by lumie31** [comment]
The title doesn't look bad to me. But since it's a tutorial of some sort, something like **Build a Todo App with Vanilla JavaScript ** might not be a bad idea
